name: Flutter app build

on: [push]

jobs:
  Flutter-Build:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout the code
    #   uses: actions/checkout@v3
    # - name: setup java repo
    #   run: sudo add-apt-repository ppa:webupd8team/java
    - name: update java repo 
      run: sudo apt-get update
    - name: install java jre
      run: sudo apt install openjdk-8-jre -y
    - name: install java jdk
      run: sudo apt install openjdk-8-jdk