name: Flutter app build

on: [push]
env:
  FLUTTER_VERSION: "2.10.0"
  GRADLE_VERSION: "7.5.1"

jobs:
  Flutter-Build:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout the code
    #   uses: actions/checkout@v3
    # - name: setup java repo
    #   run: sudo add-apt-repository ppa:webupd8team/java
    - name: update java repo 
      run: sudo apt-get update
    - name: install java jre
      run: sudo apt install openjdk-8-jre -y
    - name: install java jdk
      run: sudo apt install openjdk-8-jdk
    - name: verify java 
      run: java --version
    - name: install necessary packages
      run: sudo apt install apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common unzip git wget -y
    - name: get flutter 
      run: wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
    - name: get gradle 
      run: wget https://downloads.gradle-dn.com/distributions/gradle-${GRADLE_VERSION}-bin.zip
    - name: get commandlinetools
      run: wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
    - name: list files
      run: ls -lha
    - name: unzip files
      run: tar -xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
    - name: unzip files 
      run: unzip gradle-${GRADLE_VERSION}-bin.zip
    - name: unzip files
      run: unzip commandlinetools-linux-8512546_latest.zip
    - name: set exicutive files 
      run: echo "PATH="$PATH:${HOME}/flutter/bin"" >> $HOME/.bashrc
    - name: execute home bash 
      run: source $HOME/.bashrc
    - name: export PATH
      run: export PATH="$PATH:${HOME}/flutter/bin"
    - name: verify PATH 
      run: echo ${PATH}
    - name: verify flutter
      run: flutter doctor 
  


